### ISSUE TITLE
Lab 01 requires tufte package

### ISSUE THREAD

**Issue by saudiwin** [rstudio-education/datascience-box#87]
Hi - 

The Lab 01 RMD file requires `tufte` as a package to produce its output from the YAML header:

```
---
title: "Lab 00 - Hello R!"
output: 
  tufte::tufte_html:
    css: ../lab.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---
```

There's no mention of this package in the RMD file itself as far as I can tell. It would be great to include a line instructing students to install the package before attempting to knit & submit.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, I can certainly add this. However, note that I wouldn't expect students to be compiling this document, only the instructor. I usually post instructions separately on my course webpage (and try to make them look nice, hence the tufte style) but students work on plain R Markdown documents (to keep the cognitive load as low as possible). The starters I give the students are at https://github.com/rstudio-education/datascience-box/tree/master/course-materials/starters. 

If you are distributing the file with assignment instructions in its raw form to students, I might suggest not using the tufte style, simply because it does have some features that (in my opinion) are not super beginner-friendly (e.g. the `marginfigure` environment). Also, it uses a custom CSS, which I also avoid with new learners.

**Comment by debbieyuster** [comment]
This would be a great conversation for the [Slack](https://join.slack.com/t/dsboxworkspace/shared_invite/zt-gro0x0hh-x9JzHN0oLQayP2G0g~6Zhg) group. Just wanted to echo Mine that this file should be rendered on your end before distributing to students. Simplest on your end would be a PDF, but it's not responsive to students' screen size. I wanted HTML and settled on using GH Pages. I don't have a course website - I use my LMS (VLE). But I forked the datascience-box repo and created a new branch where I make my changes. I enabled GitHub Pages and pointed it to this development branch. This way I make changes to the assignments in RStudio, push to my development branch, and just post a link to the assignment instructions in my LMS.
If you're not serving any webpages at all, you'll run into trouble for the lecture slides, since they have some animations that won't render dynamically in PDF. Though, you can always lecture from a local HTML copy, and distribute a static PDF to students.

**Comment by saudiwin** [comment]
OK cool I think I mis-interpreted what the file was for.

**Comment by saudiwin** [comment]
I might suggest adding the word "instructions" to the lab folder as in lab-instruction so it's a bit clearer what the role of the files are :).

**Comment by mine-cetinkaya-rundel** [comment]
Sure, it's done!
